Prism\PollBundle\Entity\BasePoll:
  type: mappedSuperclass
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
    published:
      type: boolean
      nullable: false
    closed:
      type: boolean
      nullable: false
    pollSubmits:
      type: integer
      nullable: true
  oneToMany:
    questions:
      targetEntity: BaseQuestion
      mappedBy: poll
      