Prism\PollBundle\Entity\BaseOpinion:
  type: mappedSuperclass
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
    votes:
      type: integer
      nullable: true
    points:
      type: integer
      nullable: true
    score:
      type: integer
      nullable: true
    ordering:
      type: integer
      nullable: true
    absent:
      type: boolean
      nullable: true
  manyToOne:
    product:
      targetEntity: BaseQuestion
      inversedBy: opinions
      joinColumn:
        name: question_id
        referencedColumnName: id