Prism\PollBundle\Entity\BasePoll:
    properties:
        name:
            - NotBlank: ~
        opinions:
            - Valid: ~

Prism\PollBundle\Entity\BaseOpinion:
    properties:
        name:
            - NotBlank: ~