PrismPollBundle_frontend_poll_list:
    path:  /list
    defaults: { _controller: PrismPollBundle:Frontend\Poll:list }

PrismPollBundle_frontend_poll_vote:
    path:  /vote/{pollId}
    defaults: { _controller: PrismPollBundle:Frontend\Poll:vote }

PrismPollBundle_frontend_poll_results:
    path:  /results/{pollId}
    defaults: { _controller: PrismPollBundle:Frontend\Poll:results }